server:
  port: 8082

spring:

  application.name: 'authorization'
  profiles.active: local

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true
    open-in-view: false

  datasource:
    name: feeder-authorization-mysql
    url: jdbc:mysql://${datasource.host:localhost}:${datasource.port:3322}/${datasource.schema:authorization}
    username: feeder_authorization
    password: testpwd

  liquibase:
    contexts: ${spring.profiles.active}
    enabled: true

feeder:
  security:
    hierarchy.authorityPattern: >
      *:client-admin > *:client-delete > *:client-write > *:client-read
      *:admin > *:delete > *:write > *:read
  authorization:
    bcrypt-strength: 12

logging:
  level:
    #    org.springframework.security: DEBUG
    org.feeder: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
    liquibase: WARN
